[package]
name = "hoi4-modding-supporter"
version = "0.1.0"
description = "Support tool for Hearts of Iron IV modding"
authors = ["Ign1s-Reiga"]
license = "MIT"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "hoi4_modding_supporter_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
walkdir = "2"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = [
  "png",
  "jpeg",
  "gif",
  "bmp",
  "tga",
  "dds",
] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
