using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Hoi4ModdingSupporter.Util
{
    enum CountryTag
    {
        [StringValue("アフガニスタン")]
        AFG,
        [StringValue("アルバニア")]
        ALB,
        [StringValue("アルジェリア")]
        ALG,
        [StringValue("アンゴラ")]
        ANG,
        [StringValue("アラビア")]
        ARA,
        [StringValue("アルゼンチン")]
        ARG,
        [StringValue("アルメニア")]
        ARM,
        [StringValue("オーストラリア")]
        AST,
        [StringValue("オーストリア")]
        AUS,
        [StringValue("アゼルバイジャン")]
        AZR,
        [StringValue("バハマ")]
        BAH,
        [StringValue("バルト会議")]
        BAL,
        [StringValue("バングラデシュ")]
        BAN,
        [StringValue("イギリス領アンティル")]
        BAS,
        [StringValue("バイエルン")]
        BAY,
        [StringValue("ベルギー")]
        BEL,
        [StringValue("ベラルーシ")]
        BLR,
        [StringValue("ベリーズ")]
        BLZ,
        [StringValue("ボリビア")]
        BOL,
        [StringValue("ボスニア")]
        BOS,
        [StringValue("ボツワナ")]
        BOT,
        [StringValue("ブラジル")]
        BRA,
        [StringValue("ブルンジ")]
        BRD,
        [StringValue("ブルターニュ")]
        BRI,
        [StringValue("ビルマ")]
        BRM,
        [StringValue("ブルガリア")]
        BUL,
        [StringValue("ビザンツ")]
        BYZ,
        [StringValue("カンボジア")]
        CAM,
        [StringValue("カナダ")]
        CAN,
        [StringValue("中央アフリカ")]
        CAR,
        [StringValue("カタルーニャ")]
        CAT,
        [StringValue("カイエンヌ")]
        CAY,
        [StringValue("チャド")]
        CHA,
        [StringValue("中華民国")]
        CHI,
        [StringValue("チリ")]
        CHL,
        [StringValue("カメルーン")]
        CMR,
        [StringValue("コンゴ")]
        COG,
        [StringValue("コロンビア")]
        COL,
        [StringValue("コルシカ")]
        COR,
        [StringValue("コスタリカ")]
        COS,
        [StringValue("オランダ領アンティル")]
        CRC,
        [StringValue("クロアチア")]
        CRO,
        [StringValue("アメリカ連合国")]
        CSA,
        [StringValue("キューバ")]
        CUB,
        [StringValue("キプロス")]
        CYP,
        [StringValue("チェコスロバキア")]
        CZE,
    }
}
